### ISSUE TITLE
Question About Usage

### ISSUE THREAD

**Issue by kaitlyndlee** [KULeuven-COSIC/SABER#2]
Hi All,

I am sorry if this is not the correct place to post this question. I am a graduate computer science student working with PQC algorithms. I am trying to create a wrapper around Saber and need to be able to pass in a plaintext to the encryption algorithm. Is there a quick way to modify the code to be able to pass in a plaintext to the encryption algorithm (crypto_kem_enc) instead of randomly generating it? Similarly, is it possible to have the decryption algorithm (crypto_kem_dec) decrypt the ciphertext to get the plaintext? 

Thank you for taking the time to read and possibly respond to my question.

**Comment by mvanbeirendonck** [comment]
Hi Kaitlyn,

Thank you for your interest in Saber! Saber can be used in different ways. The main use case of Saber is as a IND-CCA secure key encapsulation mechanism. The functions you looked at, crypto_kem_enc and crypto_kem_dec, are for this use-case, not encryption. 

If you want to use the underlying IND-CPA secure encryption algorithm, please have a look at the functions indcpa_kem_enc and indcpa_kem_dec (in SABER_indcpa.c) instead.

For more information on these functions, have a look at the SABER round 2 submission document, which can be downloaded at https://www.esat.kuleuven.be/cosic/pqcrypto/saber/resources.html. 

Michiel
