### ISSUE TITLE
Typo in specification?

### ISSUE THREAD

**Issue by wrenna-robson** [KULeuven-COSIC/SABER#4]
In Algorithm 15 (page 31 of the current specification), on line 3, there is the following:

"Split buf into l^2 x n equal byte strings of bit length \eps_q and obtain.."

I am fairly sure this should be bit strings, as:
a) they are subsequently assigned as polynomial coordinates,
b) If the intent was that each byte string had bit length \eps_q, that would mean each bytestring was \eps_q/8 bytes, and as 1 < 13/8 < 2, natch, that seems odd,
c) Algorithm 16 uses, in a similar place, bit strings.

In addition: the implementation of GenMatrix in the reference implementation uses a more concise construction in terms of BS2POLVEC_N - while I believe they are equivalent, I was confused why there was this discrepancy between the Reference Implementation and the specification.

Best,

Wrenna

**Comment by mvanbeirendonck** [comment]
Hi Wrenna,

Thank you for your interest in Saber and for communicating issues back to us!

Regarding your first remark, this is correct. This typo is an artifact of the actual implementation, where indeed bit strings of length \eps_q=13 bits are represented as byte strings of 2 bytes. Thank you for noticing this.

Regarding your second remark, these two constructions are indeed fully equivalent. The specification document is meant to clearly and unambiguously define Saber, but not necessarily be a literal translation from C code. For example, in the implementation of Algorithm 16, you'll also see that this is partly unrolled to sample 4 coefficients at the same time. Omitting these low-level details when they are fully equivalent to the specification helps us keep clarity in the document. Please do tell us if you notice somewhere that the document is incompatible with the source code.

Best regards,
Michiel
